### ISSUE TITLE
Shared secret pub keys

### ISSUE THREAD

**Issue by metacatdud** [Electron-Cash/Nostron#1]
Hi,

Here https://github.com/Electron-Cash/Nostron/blob/nip04research/nip04research/EncryptedMessaging.py#L70 and https://github.com/Electron-Cash/Nostron/blob/nip04research/nip04research/EncryptedMessaging.py#L71

Where are those public keys coming from as I can't see them documented at the end of the file where you present the test data

Cheers!

**Comment by fyookball** [comment]
@metacatdud scroll to the bottom and look at the commented out data. That's the test keys being used. Just to be clear, it is just random keys generated for the purposes of testing the functions.

**Comment by metacatdud** [comment]
These `025ce742248cd4beea6438d8f90515fb7b4e6ca5417a54e5e7e024decdd32fbd49` and `02f168dc06f3133bfe4afe3c235a727c3a99b6fc96f61ca6c2b013091e06886422`Where do they come from?

I understand first param is the private key of each user

```py
#################################TEST DATA#####################################
##created profile: Alice1
##**private**
##hex       9b019cfe0f51b440e4a5bbf491438a933016e5fc50d05c85c5ecf439bd3dc9dd
##bech32    nsec1nvqeels02x6ype99h06fzsu2jvcpde0u2rg9epw9an6rn0fae8wsqlttmv
##**public**
##hex       f168dc06f3133bfe4afe3c235a727c3a99b6fc96f61ca6c2b013091e06886422
##bech32    npub1795dcphnzvalujh78s345unu82vmdlyk7cw2ds4szvy3up5gvs3q0q083x

##created profile: Bob1
##**private**
##hex       6e4f831b8a27aa16ad91e618ae6c857b9dcedba72ec2e1bbc5c58b307fd4dfe4
##bech32    nsec1de8cxxu2y74pdtv3ucv2umy90wwuaka89mpwrw79ck9nql75mljqcmnzre
##**public**
##hex       5ce742248cd4beea6438d8f90515fb7b4e6ca5417a54e5e7e024decdd32fbd49
##bech32    npub1tnn5yfyv6jlw5epcmrus290m0d8xef2p0f2wtelqyn0vm5e0h4ysgusfjd
###############################################################################
```

**Comment by fyookball** [comment]
Its just the pubkeys with "02" pre-pended.  Nostr keys strip that byte by default but must be added back in to use the usual libraries to perform ECDH operations.

**Comment by metacatdud** [comment]
Ooh right, right. Yeah. I forgot about that. Thanks for pointing that out.
